api:
  build: .
  environment:
    DEBUG: 'true'
  ports:
    - 5000:5000
  volumes:
    - ./code:/code
  # links:
  #   - mongodb

# mongodb:
#   image: mongo
#   volumes:
#     - ./data/mongodb:/data/db
#   ports:
#     - 27017:27017
